# docker-compose.yml
#set [Environment]::SetEnvironmentVariable("GITLAB_HOME", "$(pwd)/Gitlab101")\
#set env export GITLAB_HOME=$(pwd)/

version: '3'
services:
  web:
    image: 'drud/gitlab-ce:v0.29.1'
    restart: always
    hostname: 'localhost'
    container_name: gitlab-ce
        #environment:cd
      #GITLAB_OMNIBUS_CONFIG: |
      # external_url 'http://localhost'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - '$GITLAB_HOME/config:/etc/gitlab'
      - '$GITLAB_HOME/logs:/var/log/gitlab'
      - '$GITLAB_HOME/data:/var/opt/gitlab'
    networks:
      - gitlab
 
networks:
  gitlab:
    name: gitlab-network